name: CD

on: [push]

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-16.04
    steps:
    - name: Fetch Latest Release
      id: latest_release
      run: echo ::set-env name=release_id::$(node -e "require('https').request({hostname:'api.github.com',path:'/repos/NeKzor/SourceAutoRecord/releases',headers:{'User-Agent':'n^'}},(r)=>{let b='';r.on('data',(d)=>b+=d);r.on('end',()=>process.stdout.write(JSON.parse(b)[0].id.toString()));}).end();")
    - name: Create Asset
      run: echo test > test.txt
    - name: Upload Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/NeKzor/SourceAutoRecord/releases/${{ steps.latest_release.outputs.release_id }}/assets{?name,label}
        asset_path: test.txt
        asset_name: test.txt
        asset_content_type: application/octet-stream
