name: CD

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-16.04
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            **Installation**
            - Download:
              - [Windows]https://github.com/NeKzor/SourceAutoRecord/releases/download/${{ github.ref }}/sar-windows.zip)
              - [Linux](https://github.com/NeKzor/SourceAutoRecord/releases/download/${{ github.ref }}/sar-linux.zip)
            - Open the zip and extract the file
            - Place it into the game folder e.g. `Portal 2`
            - Open developer console and enter `plugin_load sar`

            ---

            **Changelog**
            TODO

            ---

            **Special Thanks To**
            TODO

            ---

            **Useful Links**

            [Cvar List](https://nekzor.github.io/SourceAutoRecord/doc/cvars)
            [Troubleshooting](https://nekzor.github.io/SourceAutoRecord/doc/issue)
            [Upcoming Features](https://github.com/NeKzor/SourceAutoRecord/projects/3)
          draft: false
          prerelease: false
      - name: Download Windows Artifact
          uses: actions/download-artifact@v1
          with:
            name: sar-windows
      - name: Download Linux Artifact
          uses: actions/download-artifact@v1
          with:
            name: sar-linux
      - name: Upload Windows Asset
          uses: actions/upload-release-asset@v1.0.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: sar-windows.zip
            asset_name: sar-windows.zip
            asset_content_type: application/zip
      - name: Upload Linux Asset
          uses: actions/upload-release-asset@v1.0.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: sar-linux.zip
            asset_name: sar-linux.zip
            asset_content_type: application/zip
