name: C++ CI

on: [push]

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-16.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: test
      run: echo no
