name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: make get-deps
    - name: Build
      run: make
    - name: Create artifact
      run: |
        mkdir -p artifact/
        cp sar.so artifact/sar.so
      uses: actions/upload-artifact@v1
      with:
        name: sar-linux
        path: artifact/
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SourceAutoRecordv16.sln /t:SourceAutoRecord /p:Configuration=Release /p:Platform=x86
      - name: Create artifact
        run: |
          mkdir -p artifact/
          cp bin/sar.dll artifact/sar.dll
        uses: actions/upload-artifact@v1
        with:
          name: sar-windows
          path: artifact/
